[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "digiforest_registration"
version = "0.1.0"
description = "A Python package for digiforest registration"
authors = [
    { name = "Benoit Casseau", email = "benoit@robots.ox.ac.uk" }
]
readme = "README.md"
requires-python = ">=3.7"