uav_cloud: /data/digiforest/evo/2023-05-19-15-37-55-exp01/uav_normals_for_exp01_in_utm.ply
#mls_cloud_folder: /data/digiforest/evo/2023-05-19-15-37-55-exp01/tiles_in_map
mls_cloud_folder: /home/benoit/Downloads/tiles_in_utm
offset: [-399000.00,-6786100.00,0.0]
output_folder: /home/benoit/Downloads/tiles_transformed_utm
debug: False
#pose_graph_file: /home/benoit/data/digiforest/finland/2023-05-19-15-37-55-exp01/slam_pose_graph.g2o.bck
tiles_conf_file: /home/benoit/Downloads/tiles_in_utm/tiles.csv
grid_size_row: 3
grid_size_col: 2
save_pose_graph: True
log_level: DEBUG
