uav_cloud: /data/digiforest/steim_am_rhein/2023-08-15-10-24-10-exp04/prefor_steim_am_rhein_normals_exp04_utm.ply
mls_cloud_folder: /data/digiforest/steim_am_rhein/2023-08-15-10-24-10-exp04/tiles
offset: [-490000.00,-5283300.00,0.0]
#output_folder: /data/digiforest/steim_am_rhein/2023-08-15-10-24-10-exp04/transformed_clouds_payloads_in_map
debug: False
icp_fitness_score_threshold: 0.75
