mls_cloud_folder: /data/digiforest/steim_am_rhein/new_data/d2/2023-08-15-13-12-48-exp20-d2/payload_clouds_in_map
offset: [0,0,0]
pose_graph_file: /data/digiforest/steim_am_rhein/new_data/d2/2023-08-15-13-12-48-exp20-d2/transformed_clouds_payloads_in_map/pose_graph.g2o
output_folder: /data/digiforest/steim_am_rhein/new_data/d2/2023-08-15-13-12-48-exp20-d2/optimized_payloads_in_map
load_clouds: True
tiles: False
