frontier_cloud_folder: /data/digiforest/steim_am_rhein/icra2025/m3/2023-08-15-10-55-50-exp06-m3/payload_clouds_in_map
offset: [0,0,0]
pose_graph_file: /data/digiforest/steim_am_rhein/icra2025/m3/2023-08-15-10-55-50-exp06-m3/transformed_clouds_payloads_in_map/pose_graph.g2o
output_folder: /data/digiforest/steim_am_rhein/icra2025/m3/2023-08-15-10-55-50-exp06-m3/optimized_payloads_in_map
load_clouds: True
tiles: False
