uav_cloud: /data/digiforest/steim_am_rhein/icra2025/m5/2023-08-15-11-34-36-exp09-m5/prefor_steim_am_rhein_epsg25832_map_normals.ply
mls_cloud_folder: /data/digiforest/steim_am_rhein/icra2025/m5/2023-08-15-11-34-36-exp09-m5/payload_clouds_in_map
offset: [0.0,0.0,0.0]
output_folder: /data/digiforest/steim_am_rhein/icra2025/m5/2023-08-15-11-34-36-exp09-m5/transformed_clouds_payloads_in_map
crop_mls_cloud: True
mls_feature_extraction_method: "tree_segmentation"
debug: False
min_distance_between_peaks: 4.0
max_number_of_clique: 15
pose_graph_file: /data/digiforest/steim_am_rhein/icra2025/m5/2023-08-15-11-34-36-exp09-m5/slam_pose_graph.g2o
save_pose_graph: True
icp_fitness_score_threshold: 0.75
