uav_cloud: /data/digiforest/evo/2023-05-19-15-37-55-exp01/uav_normals_for_exp01_in_map.ply
mls_cloud_folder: /data/digiforest/evo/2023-05-19-15-37-55-exp01/tiles_in_map
offset: [0,0,0.0]
output_folder: /data/digiforest/evo/2023-05-19-15-37-55-exp01/tiles_transformed_map
debug: False
#pose_graph_file: /home/benoit/data/digiforest/finland/2023-05-19-15-37-55-exp01/slam_pose_graph.g2o.bck
save_pose_graph: False
